services:
  nginx-gateway:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - solana-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env

networks:
  solana-net:
    driver: bridge
